// <auto-generated />
using Markov_Jokes.Cache;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Markov_Jokes.Migrations
{
    [DbContext(typeof(CacheContext))]
    [Migration("20190610054007_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Markov_Jokes.Cache.Model.Joke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contents")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Jokes");
                });

            modelBuilder.Entity("Markov_Jokes.Cache.Model.Weight", b =>
                {
                    b.Property<long>("Word1Id");

                    b.Property<long>("Word2Id");

                    b.Property<long>("FollowingWordId");

                    b.Property<int>("FollowingWordId1");

                    b.Property<int>("Occurrences");

                    b.Property<int>("Word1Id1");

                    b.Property<int>("Word2Id1");

                    b.HasKey("Word1Id", "Word2Id", "FollowingWordId");

                    b.HasIndex("FollowingWordId1");

                    b.HasIndex("Word1Id1");

                    b.HasIndex("Word2Id1");

                    b.ToTable("Weights");
                });

            modelBuilder.Entity("Markov_Jokes.Cache.Model.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("Content")
                        .IsUnique();

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Markov_Jokes.Cache.Model.Weight", b =>
                {
                    b.HasOne("Markov_Jokes.Cache.Model.Word", "FollowingWord")
                        .WithMany()
                        .HasForeignKey("FollowingWordId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Markov_Jokes.Cache.Model.Word", "Word1")
                        .WithMany()
                        .HasForeignKey("Word1Id1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Markov_Jokes.Cache.Model.Word", "Word2")
                        .WithMany()
                        .HasForeignKey("Word2Id1")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
